### ISSUE TITLE
readme should have more meta repo info

### ISSUE THREAD

**Issue by werdnanoslen** [axisgroup/evaluation-toolkit#22]
The readme is classically (and on Github) used as a way to get around a project (or repo). Right now, the readme. Overall it reads very well and describes process, but it's written in a narrative style, which is good for a one-sitting read-through, but there isn't an intro or quick section listing that would allow for someone to quickly reference something. There also ought to be a succinct "this is what this repo is about" bit at the beginning and a more robust one with links to each of the folders in the How To Use section.

**Comment by skokenes** [comment]
I agree. The material here is nice but probably belongs somewhere else in
repo. The home README should be more like an elevator pitch if what this
is, what it's for, how to use it.
