### ISSUE TITLE
add example images for best practices

### ISSUE THREAD

**Issue by werdnanoslen** [axisgroup/evaluation-toolkit#25]
For each section, add a visual example of a best practice and a visual example of it opposite for a this vs that effect

https://github.com/axisgroup/evaluation-toolkit/tree/master/1.%20Following%20best%20practices

**Comment by manasvil** [comment]
Can you provide one such example?

**Comment by werdnanoslen** [comment]
**Separate news from the noise**
Show a visual example of visual weight, like one of Zurb's sketches: https://zurb.com/word/visual-weight

**Content as navigation**
https://xkcd.com/214/
![image](https://user-images.githubusercontent.com/764090/32868412-2c742ece-ca40-11e7-88c6-a8fa6f12bd37.png)
