### ISSUE TITLE
Links 404 for infovis-wiki

### ISSUE THREAD

**Issue by werdnanoslen** [axisgroup/evaluation-toolkit#27]
https://github.com/axisgroup/evaluation-toolkit/tree/master/1.%20Following%20best%20practices#the-mantra-we-follow-for-seeking-visual-information

**Comment by manasvil** [comment]
which link is this again?

**Comment by werdnanoslen** [comment]
View Relationships
History
Extract

**Comment by manasvil** [comment]
Removed extraneous broken links
