### ISSUE TITLE
Fix awkward formatting in Planning the Test

### ISSUE THREAD

**Issue by werdnanoslen** [axisgroup/evaluation-toolkit#29]
https://github.com/axisgroup/evaluation-toolkit/tree/master/3.%20Planning%20the%20Test#the-complexity-in-our-stars
![image](https://user-images.githubusercontent.com/764090/32865284-703733b4-ca30-11e7-9c9f-3246c9387c1e.png)

**Comment by manasvil** [comment]
This is the brain dump section rnow

**Comment by manasvil** [comment]
did you have some feedback on the Checklist as well?

**Comment by werdnanoslen** [comment]
**Repeat for each task** uses the wrong header (should be same as others)

**Comment by werdnanoslen** [comment]
Opening paragraph doesn't need to be quoted, since it's original and you aren't citing anything.

**Comment by werdnanoslen** [comment]
Could also benefit from #23 and #24
