### ISSUE TITLE
Create a Google form template for the SUS questionnaire

### ISSUE THREAD

**Issue by manasvil** [axisgroup/evaluation-toolkit#32]
Questionnaire can be found here: https://www.usability.gov/how-to-and-tools/methods/system-usability-scale.html

Add attribution at the end
This questionnaire is based on the System Usability Scale (SUS), which was developed by John Brooke while working at Digital Equipment Corporation. © Digital Equipment Corporation, 1986.

**Comment by manasvil** [comment]
Scoring Guide: http://www.reduxly.com/writing/How-to-score-using-the-system-usability-scale.html

**Comment by liza92** [comment]
Created the form

**Comment by manasvil** [comment]
Survey:
https://docs.google.com/forms/d/e/1FAIpQLSfV_HlQoKzcB9UBJ8bQFq-rzOx1lpr5rLVVguykHLk0onnk2w/viewform

Answers: https://docs.google.com/spreadsheets/d/1Uj3wfAPWDsu69uAFu8zi4d5O0rs3G5MWt4SZru7ld-A/edit#gid=0

**Comment by usabilitest** [comment]
Here's an online version of the tool with built-in analytics: [https://www.usabilitest.com/system-usability-scale](https://www.usabilitest.com/system-usability-scale)

**Comment by sanjacob** [comment]
ඞ

**Comment by sus-imposter** [comment]
@jacobszpz _among us trap begins to play_

**Comment by DwiPanggaSinurat-119140137** [comment]
Created form
