### ISSUE TITLE
Wrapping text in code blocks to avoid horizontal scrolling

### ISSUE THREAD

**Issue by manasvil** [axisgroup/evaluation-toolkit#34]
The Information Discrimination section looks very awkward-
https://github.com/axisgroup/evaluation-toolkit/tree/master/1.Following-best-practices

**Comment by manasvil** [comment]
@skokenes help needed

**Comment by manasvil** [comment]
<img width="825" alt="screen shot 2017-11-22 at 10 25 34 am" src="https://user-images.githubusercontent.com/5871829/33135131-8b37a204-cf6f-11e7-8ac8-b8f0a9f157ff.png">
Local editor renders this properly

**Comment by jessielian** [comment]
I don't know if it's possible yet? Someone opened an issue about this a few years ago:
https://github.com/github/markup/issues/168

Looks like there are solutions/extensions on the user side to make reading easier, not necessarily on the creation side though.

**Comment by jessielian** [comment]
@manasvil why do we need code blocks? can we just use quote blocks?


> like this
> nice thing

**Comment by manasvil** [comment]
using quote blocks can be a little awkward as we also have our own commentary

**Comment by jessielian** [comment]
Manually added line breaks in code blocks
