### ISSUE TITLE
Issues uncovered during heuristic evaluation demo

### ISSUE THREAD

**Issue by manasvil** [axisgroup/evaluation-toolkit#43]
1. Agreement about what counts as a heuristic- In most UX scenarios, Nielsen and Norman's heuristic are used as an accepted usability standard. But in our case, we have a list of info vis best practices, which though generally agreed upon within the team, may not be as comprehensive as it could be. For instance, during the demo test, there was a question about "I cannot find details about my target for this month but how important is it really to know the number?" and the expert did not know how to categorize this issue. One approach is to capture these questions as miscellaneous. Another approach would be to increase the number of best practices and classifying them under the useful, usable, desirable framework.

2. Setting expectations with the expert- The expert felt the burden to find an issue in violation of every best practice or not even though the best practices section is just a guide to be able to categorize issues and also to prime them to think about potential issues. This goes to having a common understanding about the expert about what they are required to do.

3. Task make every test- There is a very important precursor to every testing method and that is to write tasks that allow for the evaluator to explore the interface. FInding issues is an incidental process of performing these tasks and hence the burden of this falls on the facilitator and this is not something the evaluators should worry about.

4. Writing task guideline- Whom you interviewed and whom you are testing with can be an important determinant of writing tasks and establishing usability criteria.
 
5. Heuristic evaluation - needs scoring method and details on how to conduct the test

**Comment by manasvil** [comment]
@g-ellsworth could you read this and add additional commentary?

**Comment by jessielian** [comment]
* added these questions to the useful section (the useful/usable/desirable section will probably always be a work in progress): 
    * Is there appropriate context that gives meaning to metrics? (i.e. benchmark, change since last time period) 
    * If something is a red flag or a reason to give the user pause, would anyone be able to tell?  
* on the expert review page, added "set expectations" & a link to the "task-writing" section

**Comment by manasvil** [comment]
can you reframe- If something is a red flag or a reason to give the user pause, would anyone be able to tell? as something that stumbles the user or something along those lines

@jessielian

**Comment by jessielian** [comment]
oh hm i think we're talking about something different?
what about
* If a there's a red flag or reason to give the user pause regarding a metric, would anyone be able to tell? Or is it hidden in the visualization?

**Comment by manasvil** [comment]
Sorry i meant stumps the user 


Sent from Yahoo Mail for iPhone


On Thursday, November 30, 2017, 9:30 AM, jessielian <notifications@github.com> wrote:


oh hm i think we're talking about something different?
what about
   
   - If a there's a red flag or reason to give the user pause regarding a metric, would anyone be able to tell? Or is it hidden in the visualization?

**Comment by manasvil** [comment]
@jessielian the heuristic evaluation template looks very good. closing this issue but I still find the language of that question confusing.
