### ISSUE TITLE
Add description to folders, right now only individual files are linked from the main README

### ISSUE THREAD

**Issue by manasvil** [axisgroup/evaluation-toolkit#47]

**Comment by jessielian** [comment]
is this one already addressed by the main readme updates? or was there something else @manasvil

**Comment by manasvil** [comment]
I was wondering if we needed to add some additional context about the folders themselves @jessielian

**Comment by jessielian** [comment]
I don’t quite get it haha, can you give example? I feel like we already did that no?

**Comment by manasvil** [comment]
haha like I was thinking if adding a short description to Setting the stage would make sense. eg. this section contains background information prior to testing. But maybe the titles are self-explanatory.

**Comment by manasvil** [comment]
closing this. I think what we have is sufficient.
