### ISSUE TITLE
Fill out Choosing the right task

### ISSUE THREAD

**Issue by manasvil** [axisgroup/evaluation-toolkit#54]
Update section: https://github.com/axisgroup/evaluation-toolkit/blob/master/3.Plan-the-test/README.md

Use: Writing the right tasks https://projects.invisionapp.com/d/main#/projects/boards/4517347/137764798
http://design.canonical.com/2013/08/usability-testing-how-do-we-design-effective-tasks/
and this summary image https://github.com/axisgroup/evaluation-toolkit/blob/master/Assets/images/task-types.png

**Comment by liza92** [comment]
added content to choosing the right task
