### ISSUE TITLE
Recruiting users section in planning the test

### ISSUE THREAD

**Issue by manasvil** [axisgroup/evaluation-toolkit#56]
Clean up based on -
http://www.webdesignerdepot.com/2015/02/how-to-test-the-usability-of-prototypes-like-a-pro/
and Charline Poirier's article https://design.canonical.com/2012/03/about-usability-testing-recruiting/

Too quote-y right now

**Comment by jessielian** [comment]
cleaned up!

**Comment by manasvil** [comment]
Did you commit changes? I do not see them. @jessielian

**Comment by jessielian** [comment]
oh weird.. that's kinda scary lol. should be good now

**Comment by manasvil** [comment]
sweet! I see it now. :)
