### ISSUE TITLE
Having trouble distinguishing the specific Usability Testing method from general user testing planning.

### ISSUE THREAD

**Issue by manasvil** [axisgroup/evaluation-toolkit#59]
Anyone have any recommendations on how to make it non-redundant?

**Comment by manasvil** [comment]
specific method: https://github.com/axisgroup/evaluation-toolkit/blob/master/4.Conduct-the-test/Research-Methods/UsabilityTesting/README.md

I would like to throw attention on the checklist https://github.com/axisgroup/evaluation-toolkit/blob/master/4.Conduct-the-test/Research-Methods/UsabilityTesting/UsabilityTestChecklist.md. Is that a substitute for the readme?

**Comment by jessielian** [comment]
Yeah I do agree, that the checklist can substitute the readme. Can call the method general usability test checklist or something

**Comment by manasvil** [comment]
perfect @jessielian added the checklist. Can we find some examples for method in action?
