### ISSUE TITLE
Make an Axis Template from these documents 

### ISSUE THREAD

**Issue by manasvil** [axisgroup/evaluation-toolkit#61]
Please read UX Pin's modification policy first https://www.uxpin.com/usability-test-kit

Add templates to https://github.com/axisgroup/evaluation-toolkit/tree/master/4.Conduct-the-test/Research-Methods/UsabilityTesting

Add links in the checklist to these documents

**Comment by jessielian** [comment]
can we remove the UsabilityTestChecklist.md file? 
and should we embed the content in that extra word doc + the relevant stuff from the invision board into the page, instead of linking out?

**Comment by manasvil** [comment]
I think we should make a word doc and add it to the folder and then in the README add a direct link to our local copy. 

And the Invision link I am going to remove.

**Comment by jessielian** [comment]
i looked through the files in the test kit and i think they work pretty well as is - not sure if it makes sense to try to turn them into "axis" versions?

**Comment by manasvil** [comment]
Alright! Thank you.
