### ISSUE TITLE
use markdown table instead of screenshot

### ISSUE THREAD

**Issue by werdnanoslen** [axisgroup/evaluation-toolkit#63]
The table in step 8 of https://github.com/axisgroup/evaluation-toolkit/blob/master/4.Conduct-the-test/Research-Methods/ExpertReview/README.md is visually very different and distracting, but it's simple enough that it could be constructed using a markdown table.

Like this:

| A | B | C | 
|---|---|---|
| 1 | 2 | 3 |

You can use a table generator like this, too: https://www.tablesgenerator.com/markdown_tables

**Comment by manasvil** [comment]
Sweet! Fixed. Thanks for that resource
