### ISSUE TITLE
lists should just be numbered, not bulleted and numbered

### ISSUE THREAD

**Issue by werdnanoslen** [axisgroup/evaluation-toolkit#65]
Don't use both bullets and numbers in https://github.com/axisgroup/evaluation-toolkit/blob/master/4.Conduct-the-test/Research-Methods/ExpertReview/README.md

Just use a numbered (ordered) list starting at zero using html, like this:

<ol start="0">
  <li>Item 0</li>
  <li>Item 1</li>
  <li>Item 2</li>
</ol>

**Comment by manasvil** [comment]
can you check now?

**Comment by werdnanoslen** [comment]
Much better 👍
----
Andrew Nelson
andyhub.com
832-677-7180
(sent from mobile)
